version: "3.9"

services:

  inventory-service:
    image: vzateychuk/inventory-service:0.0.1
    container_name: inventory-service
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 27017
      DB_NAME: admin
      DB_USER: admin
      DB_PWD: admin
    depends_on:
      - mongo-db

  shipping-service:
    image: vzateychuk/shipping-service:0.0.1
    container_name: shipping-service
    restart: on-failure
    ports:
      - "8082:8080"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 27017
      DB_NAME: admin
      DB_USER: admin
      DB_PWD: admin
      USER_SERVICE_API: http://host.docker.internal:8081/users/
    depends_on:
      - mongo-db

  order-service:
    image: vzateychuk/order-service:0.0.1
    container_name: order-service
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 27017
      DB_NAME: admin
      DB_USER: admin
      DB_PWD: admin
      USER_SERVICE_API: http://host.docker.internal:8081/users/
    depends_on:
      - mongo-db
      - inventory-service
      - shipping-service

  mongo-db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 9081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
    depends_on:
      - mongo-db
