springdoc:
  swagger-ui:
    doc-expansion: none
    disable-swagger-default-url: true

logging:
  level:
    root: INFO

server:
  servlet:
    context-path: "/api/${spring.application.api-version}"

spring:
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      username: ${DB_USER}
      password: ${DB_PWD}
      database: ${DB_NAME}
      authSource: ${DB_NAME}
  application:
    name: order-app
    api-version: "v1"

client:
  inventory:
    baseUrl: "http://localhost:8081/api/v1"
  shipment:
    baseUrl: "http://localhost:8082/api/v1"