logging:
  level:
    root: INFO

spring:
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      username: ${DB_USER}
      password: ${DB_PWD}
      database: ${DB_NAME}
      authSource: ${DB_NAME}
  application:
    name: inventory-app
    api-version: "v1"
