springdoc:
  swagger-ui:
    doc-expansion: none
    disable-swagger-default-url: true

logging:
  level:
    root: INFO

server:
  port: 8081
  servlet:
    context-path: "/api/${spring.application.api-version}"

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: admin
      database: admin
      authSource: admin
  application:
    name: inventory-app
    api-version: "v1"

# data:
#  mongodb:
#    uri=mongodb://localhost:27017/inventory:
